# Generated by Django 5.2.3 on 2025-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='working_hours',
            field=models.DateTimeField(),
        ),
    ]
