# Generated by Django 5.2.3 on 2025-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='working_hours',
            field=models.TimeField(),
        ),
    ]
